<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTdmCLu7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTdmCLu7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTdmCLu7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTdmCLu7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTdmCLu7\App_KernelDevDebugContainer([
    'container.build_hash' => 'TdmCLu7',
    'container.build_id' => '0b86fb16',
    'container.build_time' => 1738836313,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTdmCLu7');
