<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0B0SMQp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0B0SMQp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0B0SMQp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0B0SMQp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0B0SMQp\App_KernelDevDebugContainer([
    'container.build_hash' => '0B0SMQp',
    'container.build_id' => '43961d89',
    'container.build_time' => 1739657151,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container0B0SMQp');
